### PR TITLE
that.$button.data('bs.dropdown') is undefined with bootstrap 4.0.0-alpha.5

### PR DESCRIPTION
**Pull request by procedurallygenerated**
that.$button.data('bs.dropdown') returns undefined and breaks the selectpicker. It does not even open. 

This is one of my first pull requests, let me know if I need to do anything else.

Thanks

### CODE REVIEW

**Comment by caseyjhol** [comment]
Can you link me to a live demo of this particular issue? Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.

**Comment by procedurallygenerated** [comment]
Hey,

https://jsfiddle.net/r1Ljbq7k/8/

Try opening the select box, you should see the error in the console.

Thanks

**Comment by procedurallygenerated** [comment]
You should be able to see the includes in the index.html in the fiddle,

jquery 3.3.1
bootstrap 4.0.5
bootstrap-select 1.13.0

I'm seeing this error on chrome 65.0.3325.181 on osx 10.13.2

Thanks for the awesome library

**Comment by caseyjhol** [comment]
It looks like you're using Bootstrap v4.0.0-alpha.5. There are several newer Bootstrap versions since then with tons of changes, including a switch to using Popper instead of Tether. Please try upgrading to v4.0.0 and see if the problem persists.

**Comment by caseyjhol** [comment]
Have confirmed the issue does not exist with a stable version of Bootstrap: https://jsfiddle.net/r1Ljbq7k/13/. 

Glad you like the library! Please star and watch for future updates!

**Pull request closed without merging**
